a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
c=int(input("Enter third number: "))
print("The value of a<b and a<c is",a<b and a<c)
print("The value of a<b or a<c is",a<b or a<c)
print("The value of not(a<b) is",not(a<b))